In [122]:
import pandas as pd

In [123]:
df = pd.read_csv("messy_gdp_dataset.csv")

In [124]:
df.head()

  Country   year      gdp_value
0   France   2005            NaN
1   india    2000    910,000,000
2   india    2000    910,000,000
3  germany   2003  2,662,000,000
4   india    2005  3,494,000,000

In [125]:
df.columns

Index([' Country ', ' year ', ' gdp_value '], dtype='object')

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0    Country     65 non-null     object
 1    year        65 non-null     int64
 2    gdp_value   55 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.7+ KB

In [127]:
df.isna().sum()

Country        0
year           0
gdp_value     10
dtype: int64

# Remove Extra Spaces

In [129]:
df.columns = df.columns.str.strip()

In [130]:
df["gdp_value"].head()

0              NaN
1      910,000,000
2      910,000,000
3    2,662,000,000
4    3,494,000,000
Name: gdp_value, dtype: object

# changing data type of the gdp_value object to float

In [132]:
df["gdp_value"] = df["gdp_value"].replace(r'[^0-9.]', '',regex = True)

In [133]:
df["gdp_value"] = df["gdp_value"].astype(float)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    65 non-null     object
 1   year       65 non-null     int64
 2   gdp_value  55 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.7+ KB

# Remove Duplicate()

In [136]:
df = df.drop_duplicates()

In [137]:
df

                 Country  year     gdp_value
0                 France  2005           NaN
1                 india   2000  9.100000e+08
3                germany  2003  2.662000e+09
4                 india   2005  3.494000e+09
6                  CHINA  2004  4.167000e+09
7                  CHINA  2000  2.483000e+09
8                  CHINA  2001  1.234000e+09
9       Egypt, Arab Rep.  2000  1.949000e+09
10      Egypt, Arab Rep.  2003           NaN
11                   USA  2003           NaN
12  Hong Kong SAR, China  2005           NaN
14      Egypt, Arab Rep.  2004  3.606000e+09
15          South Africa  2001           NaN
16                india   2003           NaN
17                 CHINA  2005           NaN
18  Hong Kong SAR, China  2004  2.413000e+09
19                   USA  2002  1.800000e+08
20                   USA  2000  3.221000e+09
22                india   2004  4.476000e+09
23                France  2000  2.606000e+09
24  Hong Kong SAR, China  2000  6.960000e+08
25                Brazil  2001  5.240000e+08
26               Nigeria  2001  3.993000e+09
27               Nigeria  2004  3.511000e+09
28               Nigeria  2002  3.123000e+09
29                France  2002  4.064000e+09
30      Egypt, Arab Rep.  2001  1.317000e+09
31               germany  2002  2.874000e+09
33                 CHINA  2003  3.435000e+09
34          South Africa  2003  2.784000e+09
35          South Africa  2002  2.390000e+08
36          South Africa  2000  1.025000e+09
37               germany  2005  1.528000e+09
38                   USA  2005  2.441000e+09
39      Egypt, Arab Rep.  2002  1.578000e+09
40               Nigeria  2005  2.663000e+09
41               germany  2004  1.413000e+09
42  Hong Kong SAR, China  2001  2.938000e+09
43          South Africa  2005  4.708000e+09
44               germany  2001           NaN
45                France  2001  8.250000e+08
46                india   2001  3.822000e+09
47                Brazil  2003  2.608000e+09
48                india   2002  3.142000e+09
49                France  2004  3.202000e+09
50  Hong Kong SAR, China  2003  6.500000e+08
51      Egypt, Arab Rep.  2005           NaN
52                Brazil  2005  2.797000e+09
53               Nigeria  2000  1.635000e+09
54                   USA  2004  8.190000e+08
55                Brazil  2004  2.097000e+09
56                Brazil  2000  2.954000e+09
57               Nigeria  2003  1.071000e+09
58  Hong Kong SAR, China  2002  2.485000e+09
59                Brazil  2002  1.132000e+09
60                   USA  2001  2.969000e+09
61               germany  2000  2.910000e+08
62                 CHINA  2002  4.605000e+09
63          South Africa  2004           NaN
64                France  2003  8.400000e+07

In [138]:
df.isna().sum()

Country       0
year          0
gdp_value    10
dtype: int64

In [139]:
df["gdp_value"].mean()

np.float64(2308860000.0)

In [140]:
df["gdp_value"] = df["gdp_value"].fillna(df["gdp_value"].mean())

In [141]:
df.isna().sum()

Country      0
year         0
gdp_value    0
dtype: int64

# Fixing formating issue

In [143]:
df["Country"].head(10)

0               France
1               india
3              germany
4               india
6                CHINA
7                CHINA
8                CHINA
9     Egypt, Arab Rep.
10    Egypt, Arab Rep.
11                 USA
Name: Country, dtype: object

In [144]:
df["Country"] = df["Country"].str.strip()

In [145]:
df["Country"].head(10)

0               France
1                india
3              germany
4                india
6                CHINA
7                CHINA
8                CHINA
9     Egypt, Arab Rep.
10    Egypt, Arab Rep.
11                 USA
Name: Country, dtype: object

In [146]:
df["Country"] = df["Country"].str.lower()

In [147]:
df["Country"].unique()

array(['france', 'india', 'germany', 'china', 'egypt, arab rep.', 'usa',
       'hong kong sar, china', 'south africa', 'brazil', 'nigeria'],
      dtype=object)

In [148]:
df["Country"].head(10)

0               france
1                india
3              germany
4                india
6                china
7                china
8                china
9     egypt, arab rep.
10    egypt, arab rep.
11                 usa
Name: Country, dtype: object

In [149]:
df["Country"] = df["Country"].replace({
    "france":"France",
    "india":"India",
    "germany":"Germany",
    "china":"China",
    "egypt, arab rep.":"Egypt",
    "usa":"Usa",
    "hong kong sar, china":"Hong Kong",
    "south africa":"South Africa",
    "brazil":"Brazil",
    "nigeria":"Nigeria"
})

In [151]:
df.head(10)

    Country  year     gdp_value
0    France  2005  2.308860e+09
1     India  2000  9.100000e+08
3   Germany  2003  2.662000e+09
4     India  2005  3.494000e+09
6     China  2004  4.167000e+09
7     China  2000  2.483000e+09
8     China  2001  1.234000e+09
9     Egypt  2000  1.949000e+09
10    Egypt  2003  2.308860e+09
11      Usa  2003  2.308860e+09

# Final Check

In [153]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 64
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    60 non-null     object
 1   year       60 non-null     int64
 2   gdp_value  60 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.9+ KB

In [154]:
df.isna().sum()

Country      0
year         0
gdp_value    0
dtype: int64

In [155]:
df

         Country  year     gdp_value
0         France  2005  2.308860e+09
1          India  2000  9.100000e+08
3        Germany  2003  2.662000e+09
4          India  2005  3.494000e+09
6          China  2004  4.167000e+09
7          China  2000  2.483000e+09
8          China  2001  1.234000e+09
9          Egypt  2000  1.949000e+09
10         Egypt  2003  2.308860e+09
11           Usa  2003  2.308860e+09
12     Hong Kong  2005  2.308860e+09
14         Egypt  2004  3.606000e+09
15  South Africa  2001  2.308860e+09
16         India  2003  2.308860e+09
17         China  2005  2.308860e+09
18     Hong Kong  2004  2.413000e+09
19           Usa  2002  1.800000e+08
20           Usa  2000  3.221000e+09
22         India  2004  4.476000e+09
23        France  2000  2.606000e+09
24     Hong Kong  2000  6.960000e+08
25        Brazil  2001  5.240000e+08
26       Nigeria  2001  3.993000e+09
27       Nigeria  2004  3.511000e+09
28       Nigeria  2002  3.123000e+09
29        France  2002  4.064000e+09
30         Egypt  2001  1.317000e+09
31       Germany  2002  2.874000e+09
33         China  2003  3.435000e+09
34  South Africa  2003  2.784000e+09
35  South Africa  2002  2.390000e+08
36  South Africa  2000  1.025000e+09
37       Germany  2005  1.528000e+09
38           Usa  2005  2.441000e+09
39         Egypt  2002  1.578000e+09
40       Nigeria  2005  2.663000e+09
41       Germany  2004  1.413000e+09
42     Hong Kong  2001  2.938000e+09
43  South Africa  2005  4.708000e+09
44       Germany  2001  2.308860e+09
45        France  2001  8.250000e+08
46         India  2001  3.822000e+09
47        Brazil  2003  2.608000e+09
48         India  2002  3.142000e+09
49        France  2004  3.202000e+09
50     Hong Kong  2003  6.500000e+08
51         Egypt  2005  2.308860e+09
52        Brazil  2005  2.797000e+09
53       Nigeria  2000  1.635000e+09
54           Usa  2004  8.190000e+08
55        Brazil  2004  2.097000e+09
56        Brazil  2000  2.954000e+09
57       Nigeria  2003  1.071000e+09
58     Hong Kong  2002  2.485000e+09
59        Brazil  2002  1.132000e+09
60           Usa  2001  2.969000e+09
61       Germany  2000  2.910000e+08
62         China  2002  4.605000e+09
63  South Africa  2004  2.308860e+09
64        France  2003  8.400000e+07

In [160]:
df.sort_values(by = ["Country","year"],ascending = True,ignore_index = True)

         Country  year     gdp_value
0         Brazil  2000  2.954000e+09
1         Brazil  2001  5.240000e+08
2         Brazil  2002  1.132000e+09
3         Brazil  2003  2.608000e+09
4         Brazil  2004  2.097000e+09
5         Brazil  2005  2.797000e+09
6          China  2000  2.483000e+09
7          China  2001  1.234000e+09
8          China  2002  4.605000e+09
9          China  2003  3.435000e+09
10         China  2004  4.167000e+09
11         China  2005  2.308860e+09
12         Egypt  2000  1.949000e+09
13         Egypt  2001  1.317000e+09
14         Egypt  2002  1.578000e+09
15         Egypt  2003  2.308860e+09
16         Egypt  2004  3.606000e+09
17         Egypt  2005  2.308860e+09
18        France  2000  2.606000e+09
19        France  2001  8.250000e+08
20        France  2002  4.064000e+09
21        France  2003  8.400000e+07
22        France  2004  3.202000e+09
23        France  2005  2.308860e+09
24       Germany  2000  2.910000e+08
25       Germany  2001  2.308860e+09
26       Germany  2002  2.874000e+09
27       Germany  2003  2.662000e+09
28       Germany  2004  1.413000e+09
29       Germany  2005  1.528000e+09
30     Hong Kong  2000  6.960000e+08
31     Hong Kong  2001  2.938000e+09
32     Hong Kong  2002  2.485000e+09
33     Hong Kong  2003  6.500000e+08
34     Hong Kong  2004  2.413000e+09
35     Hong Kong  2005  2.308860e+09
36         India  2000  9.100000e+08
37         India  2001  3.822000e+09
38         India  2002  3.142000e+09
39         India  2003  2.308860e+09
40         India  2004  4.476000e+09
41         India  2005  3.494000e+09
42       Nigeria  2000  1.635000e+09
43       Nigeria  2001  3.993000e+09
44       Nigeria  2002  3.123000e+09
45       Nigeria  2003  1.071000e+09
46       Nigeria  2004  3.511000e+09
47       Nigeria  2005  2.663000e+09
48  South Africa  2000  1.025000e+09
49  South Africa  2001  2.308860e+09
50  South Africa  2002  2.390000e+08
51  South Africa  2003  2.784000e+09
52  South Africa  2004  2.308860e+09
53  South Africa  2005  4.708000e+09
54           Usa  2000  3.221000e+09
55           Usa  2001  2.969000e+09
56           Usa  2002  1.800000e+08
57           Usa  2003  2.308860e+09
58           Usa  2004  8.190000e+08
59           Usa  2005  2.441000e+09